# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uber/cadence/admin/v1/cluster.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uber/cadence/admin/v1/cluster.proto',
  package='uber.cadence.admin.v1',
  syntax='proto3',
  serialized_options=b'Z5github.com/uber/cadence-idl/go/proto/admin/v1;adminv1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#uber/cadence/admin/v1/cluster.proto\x12\x15uber.cadence.admin.v1\"\x1c\n\x08HostInfo\x12\x10\n\x08identity\x18\x01 \x01(\t\"`\n\x08RingInfo\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x14\n\x0cmember_count\x18\x02 \x01(\x05\x12\x30\n\x07members\x18\x03 \x03(\x0b\x32\x1f.uber.cadence.admin.v1.HostInfo\"\x92\x01\n\x0eMembershipInfo\x12\x35\n\x0c\x63urrent_host\x18\x01 \x01(\x0b\x32\x1f.uber.cadence.admin.v1.HostInfo\x12\x19\n\x11reachable_members\x18\x02 \x03(\t\x12.\n\x05rings\x18\x03 \x03(\x0b\x32\x1f.uber.cadence.admin.v1.RingInfo\"]\n\x0f\x44omainCacheInfo\x12#\n\x1bnum_of_items_in_cache_by_id\x18\x01 \x01(\x03\x12%\n\x1dnum_of_items_in_cache_by_name\x18\x02 \x01(\x03\"0\n\x12PersistenceSetting\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"2\n\x12PersistenceFeature\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\"\x9c\x01\n\x0fPersistenceInfo\x12\x0f\n\x07\x62\x61\x63kend\x18\x01 \x01(\t\x12;\n\x08settings\x18\x02 \x03(\x0b\x32).uber.cadence.admin.v1.PersistenceSetting\x12;\n\x08\x66\x65\x61tures\x18\x03 \x03(\x0b\x32).uber.cadence.admin.v1.PersistenceFeatureB7Z5github.com/uber/cadence-idl/go/proto/admin/v1;adminv1b\x06proto3'
)




_HOSTINFO = _descriptor.Descriptor(
  name='HostInfo',
  full_name='uber.cadence.admin.v1.HostInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identity', full_name='uber.cadence.admin.v1.HostInfo.identity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=90,
)


_RINGINFO = _descriptor.Descriptor(
  name='RingInfo',
  full_name='uber.cadence.admin.v1.RingInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='role', full_name='uber.cadence.admin.v1.RingInfo.role', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='member_count', full_name='uber.cadence.admin.v1.RingInfo.member_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='members', full_name='uber.cadence.admin.v1.RingInfo.members', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=188,
)


_MEMBERSHIPINFO = _descriptor.Descriptor(
  name='MembershipInfo',
  full_name='uber.cadence.admin.v1.MembershipInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_host', full_name='uber.cadence.admin.v1.MembershipInfo.current_host', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reachable_members', full_name='uber.cadence.admin.v1.MembershipInfo.reachable_members', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rings', full_name='uber.cadence.admin.v1.MembershipInfo.rings', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=337,
)


_DOMAINCACHEINFO = _descriptor.Descriptor(
  name='DomainCacheInfo',
  full_name='uber.cadence.admin.v1.DomainCacheInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_of_items_in_cache_by_id', full_name='uber.cadence.admin.v1.DomainCacheInfo.num_of_items_in_cache_by_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_of_items_in_cache_by_name', full_name='uber.cadence.admin.v1.DomainCacheInfo.num_of_items_in_cache_by_name', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=432,
)


_PERSISTENCESETTING = _descriptor.Descriptor(
  name='PersistenceSetting',
  full_name='uber.cadence.admin.v1.PersistenceSetting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='uber.cadence.admin.v1.PersistenceSetting.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='uber.cadence.admin.v1.PersistenceSetting.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=482,
)


_PERSISTENCEFEATURE = _descriptor.Descriptor(
  name='PersistenceFeature',
  full_name='uber.cadence.admin.v1.PersistenceFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='uber.cadence.admin.v1.PersistenceFeature.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='uber.cadence.admin.v1.PersistenceFeature.enabled', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=534,
)


_PERSISTENCEINFO = _descriptor.Descriptor(
  name='PersistenceInfo',
  full_name='uber.cadence.admin.v1.PersistenceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='backend', full_name='uber.cadence.admin.v1.PersistenceInfo.backend', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='settings', full_name='uber.cadence.admin.v1.PersistenceInfo.settings', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='features', full_name='uber.cadence.admin.v1.PersistenceInfo.features', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=537,
  serialized_end=693,
)

_RINGINFO.fields_by_name['members'].message_type = _HOSTINFO
_MEMBERSHIPINFO.fields_by_name['current_host'].message_type = _HOSTINFO
_MEMBERSHIPINFO.fields_by_name['rings'].message_type = _RINGINFO
_PERSISTENCEINFO.fields_by_name['settings'].message_type = _PERSISTENCESETTING
_PERSISTENCEINFO.fields_by_name['features'].message_type = _PERSISTENCEFEATURE
DESCRIPTOR.message_types_by_name['HostInfo'] = _HOSTINFO
DESCRIPTOR.message_types_by_name['RingInfo'] = _RINGINFO
DESCRIPTOR.message_types_by_name['MembershipInfo'] = _MEMBERSHIPINFO
DESCRIPTOR.message_types_by_name['DomainCacheInfo'] = _DOMAINCACHEINFO
DESCRIPTOR.message_types_by_name['PersistenceSetting'] = _PERSISTENCESETTING
DESCRIPTOR.message_types_by_name['PersistenceFeature'] = _PERSISTENCEFEATURE
DESCRIPTOR.message_types_by_name['PersistenceInfo'] = _PERSISTENCEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HostInfo = _reflection.GeneratedProtocolMessageType('HostInfo', (_message.Message,), {
  'DESCRIPTOR' : _HOSTINFO,
  '__module__' : 'uber.cadence.admin.v1.cluster_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.admin.v1.HostInfo)
  })
_sym_db.RegisterMessage(HostInfo)

RingInfo = _reflection.GeneratedProtocolMessageType('RingInfo', (_message.Message,), {
  'DESCRIPTOR' : _RINGINFO,
  '__module__' : 'uber.cadence.admin.v1.cluster_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.admin.v1.RingInfo)
  })
_sym_db.RegisterMessage(RingInfo)

MembershipInfo = _reflection.GeneratedProtocolMessageType('MembershipInfo', (_message.Message,), {
  'DESCRIPTOR' : _MEMBERSHIPINFO,
  '__module__' : 'uber.cadence.admin.v1.cluster_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.admin.v1.MembershipInfo)
  })
_sym_db.RegisterMessage(MembershipInfo)

DomainCacheInfo = _reflection.GeneratedProtocolMessageType('DomainCacheInfo', (_message.Message,), {
  'DESCRIPTOR' : _DOMAINCACHEINFO,
  '__module__' : 'uber.cadence.admin.v1.cluster_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.admin.v1.DomainCacheInfo)
  })
_sym_db.RegisterMessage(DomainCacheInfo)

PersistenceSetting = _reflection.GeneratedProtocolMessageType('PersistenceSetting', (_message.Message,), {
  'DESCRIPTOR' : _PERSISTENCESETTING,
  '__module__' : 'uber.cadence.admin.v1.cluster_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.admin.v1.PersistenceSetting)
  })
_sym_db.RegisterMessage(PersistenceSetting)

PersistenceFeature = _reflection.GeneratedProtocolMessageType('PersistenceFeature', (_message.Message,), {
  'DESCRIPTOR' : _PERSISTENCEFEATURE,
  '__module__' : 'uber.cadence.admin.v1.cluster_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.admin.v1.PersistenceFeature)
  })
_sym_db.RegisterMessage(PersistenceFeature)

PersistenceInfo = _reflection.GeneratedProtocolMessageType('PersistenceInfo', (_message.Message,), {
  'DESCRIPTOR' : _PERSISTENCEINFO,
  '__module__' : 'uber.cadence.admin.v1.cluster_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.admin.v1.PersistenceInfo)
  })
_sym_db.RegisterMessage(PersistenceInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
