# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uber/cadence/api/v1/service_meta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uber/cadence/api/v1/service_meta.proto',
  package='uber.cadence.api.v1',
  syntax='proto3',
  serialized_options=b'\n\027com.uber.cadence.api.v1B\020MetaServiceProtoP\001Z1github.com/uber/cadence-idl/go/proto/api/v1;apiv1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&uber/cadence/api/v1/service_meta.proto\x12\x13uber.cadence.api.v1\"\x0f\n\rHealthRequest\"-\n\x0eHealthResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\\\n\x07MetaAPI\x12Q\n\x06Health\x12\".uber.cadence.api.v1.HealthRequest\x1a#.uber.cadence.api.v1.HealthResponseB`\n\x17\x63om.uber.cadence.api.v1B\x10MetaServiceProtoP\x01Z1github.com/uber/cadence-idl/go/proto/api/v1;apiv1b\x06proto3'
)




_HEALTHREQUEST = _descriptor.Descriptor(
  name='HealthRequest',
  full_name='uber.cadence.api.v1.HealthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=78,
)


_HEALTHRESPONSE = _descriptor.Descriptor(
  name='HealthResponse',
  full_name='uber.cadence.api.v1.HealthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='uber.cadence.api.v1.HealthResponse.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='uber.cadence.api.v1.HealthResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['HealthRequest'] = _HEALTHREQUEST
DESCRIPTOR.message_types_by_name['HealthResponse'] = _HEALTHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HealthRequest = _reflection.GeneratedProtocolMessageType('HealthRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHREQUEST,
  '__module__' : 'uber.cadence.api.v1.service_meta_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.HealthRequest)
  })
_sym_db.RegisterMessage(HealthRequest)

HealthResponse = _reflection.GeneratedProtocolMessageType('HealthResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHRESPONSE,
  '__module__' : 'uber.cadence.api.v1.service_meta_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.HealthResponse)
  })
_sym_db.RegisterMessage(HealthResponse)


DESCRIPTOR._options = None

_METAAPI = _descriptor.ServiceDescriptor(
  name='MetaAPI',
  full_name='uber.cadence.api.v1.MetaAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=127,
  serialized_end=219,
  methods=[
  _descriptor.MethodDescriptor(
    name='Health',
    full_name='uber.cadence.api.v1.MetaAPI.Health',
    index=0,
    containing_service=None,
    input_type=_HEALTHREQUEST,
    output_type=_HEALTHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_METAAPI)

DESCRIPTOR.services_by_name['MetaAPI'] = _METAAPI

# @@protoc_insertion_point(module_scope)
