# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uber/cadence/api/v1/visibility.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from uber.cadence.api.v1 import workflow_pb2 as uber_dot_cadence_dot_api_dot_v1_dot_workflow__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='uber/cadence/api/v1/visibility.proto',
  package='uber.cadence.api.v1',
  syntax='proto3',
  serialized_options=b'\n\027com.uber.cadence.api.v1B\017VisibilityProtoP\001Z1github.com/uber/cadence-idl/go/proto/api/v1;apiv1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$uber/cadence/api/v1/visibility.proto\x12\x13uber.cadence.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"uber/cadence/api/v1/workflow.proto\">\n\x17WorkflowExecutionFilter\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\"\"\n\x12WorkflowTypeFilter\x12\x0c\n\x04name\x18\x01 \x01(\t\"u\n\x0fStartTimeFilter\x12\x31\n\rearliest_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0blatest_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"Q\n\x0cStatusFilter\x12\x41\n\x06status\x18\x01 \x01(\x0e\x32\x31.uber.cadence.api.v1.WorkflowExecutionCloseStatus*\xea\x01\n\x10IndexedValueType\x12\x1e\n\x1aINDEXED_VALUE_TYPE_INVALID\x10\x00\x12\x1d\n\x19INDEXED_VALUE_TYPE_STRING\x10\x01\x12\x1e\n\x1aINDEXED_VALUE_TYPE_KEYWORD\x10\x02\x12\x1a\n\x16INDEXED_VALUE_TYPE_INT\x10\x03\x12\x1d\n\x19INDEXED_VALUE_TYPE_DOUBLE\x10\x04\x12\x1b\n\x17INDEXED_VALUE_TYPE_BOOL\x10\x05\x12\x1f\n\x1bINDEXED_VALUE_TYPE_DATETIME\x10\x06\x42_\n\x17\x63om.uber.cadence.api.v1B\x0fVisibilityProtoP\x01Z1github.com/uber/cadence-idl/go/proto/api/v1;apiv1b\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,uber_dot_cadence_dot_api_dot_v1_dot_workflow__pb2.DESCRIPTOR,])

_INDEXEDVALUETYPE = _descriptor.EnumDescriptor(
  name='IndexedValueType',
  full_name='uber.cadence.api.v1.IndexedValueType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INDEXED_VALUE_TYPE_INVALID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INDEXED_VALUE_TYPE_STRING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INDEXED_VALUE_TYPE_KEYWORD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INDEXED_VALUE_TYPE_INT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INDEXED_VALUE_TYPE_DOUBLE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INDEXED_VALUE_TYPE_BOOL', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INDEXED_VALUE_TYPE_DATETIME', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=433,
  serialized_end=667,
)
_sym_db.RegisterEnumDescriptor(_INDEXEDVALUETYPE)

IndexedValueType = enum_type_wrapper.EnumTypeWrapper(_INDEXEDVALUETYPE)
INDEXED_VALUE_TYPE_INVALID = 0
INDEXED_VALUE_TYPE_STRING = 1
INDEXED_VALUE_TYPE_KEYWORD = 2
INDEXED_VALUE_TYPE_INT = 3
INDEXED_VALUE_TYPE_DOUBLE = 4
INDEXED_VALUE_TYPE_BOOL = 5
INDEXED_VALUE_TYPE_DATETIME = 6



_WORKFLOWEXECUTIONFILTER = _descriptor.Descriptor(
  name='WorkflowExecutionFilter',
  full_name='uber.cadence.api.v1.WorkflowExecutionFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflow_id', full_name='uber.cadence.api.v1.WorkflowExecutionFilter.workflow_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='run_id', full_name='uber.cadence.api.v1.WorkflowExecutionFilter.run_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=192,
)


_WORKFLOWTYPEFILTER = _descriptor.Descriptor(
  name='WorkflowTypeFilter',
  full_name='uber.cadence.api.v1.WorkflowTypeFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='uber.cadence.api.v1.WorkflowTypeFilter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=228,
)


_STARTTIMEFILTER = _descriptor.Descriptor(
  name='StartTimeFilter',
  full_name='uber.cadence.api.v1.StartTimeFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='earliest_time', full_name='uber.cadence.api.v1.StartTimeFilter.earliest_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latest_time', full_name='uber.cadence.api.v1.StartTimeFilter.latest_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=347,
)


_STATUSFILTER = _descriptor.Descriptor(
  name='StatusFilter',
  full_name='uber.cadence.api.v1.StatusFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='uber.cadence.api.v1.StatusFilter.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=430,
)

_STARTTIMEFILTER.fields_by_name['earliest_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STARTTIMEFILTER.fields_by_name['latest_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STATUSFILTER.fields_by_name['status'].enum_type = uber_dot_cadence_dot_api_dot_v1_dot_workflow__pb2._WORKFLOWEXECUTIONCLOSESTATUS
DESCRIPTOR.message_types_by_name['WorkflowExecutionFilter'] = _WORKFLOWEXECUTIONFILTER
DESCRIPTOR.message_types_by_name['WorkflowTypeFilter'] = _WORKFLOWTYPEFILTER
DESCRIPTOR.message_types_by_name['StartTimeFilter'] = _STARTTIMEFILTER
DESCRIPTOR.message_types_by_name['StatusFilter'] = _STATUSFILTER
DESCRIPTOR.enum_types_by_name['IndexedValueType'] = _INDEXEDVALUETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkflowExecutionFilter = _reflection.GeneratedProtocolMessageType('WorkflowExecutionFilter', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWEXECUTIONFILTER,
  '__module__' : 'uber.cadence.api.v1.visibility_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.WorkflowExecutionFilter)
  })
_sym_db.RegisterMessage(WorkflowExecutionFilter)

WorkflowTypeFilter = _reflection.GeneratedProtocolMessageType('WorkflowTypeFilter', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWTYPEFILTER,
  '__module__' : 'uber.cadence.api.v1.visibility_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.WorkflowTypeFilter)
  })
_sym_db.RegisterMessage(WorkflowTypeFilter)

StartTimeFilter = _reflection.GeneratedProtocolMessageType('StartTimeFilter', (_message.Message,), {
  'DESCRIPTOR' : _STARTTIMEFILTER,
  '__module__' : 'uber.cadence.api.v1.visibility_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.StartTimeFilter)
  })
_sym_db.RegisterMessage(StartTimeFilter)

StatusFilter = _reflection.GeneratedProtocolMessageType('StatusFilter', (_message.Message,), {
  'DESCRIPTOR' : _STATUSFILTER,
  '__module__' : 'uber.cadence.api.v1.visibility_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.StatusFilter)
  })
_sym_db.RegisterMessage(StatusFilter)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
