# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cadence.api.v1 import service_schedule_pb2 as cadence_dot_api_dot_v1_dot_service__schedule__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cadence/api/v1/service_schedule_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScheduleAPIStub(object):
    """ScheduleAPI provides APIs for managing schedules.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSchedule = channel.unary_unary(
                '/uber.cadence.api.v1.ScheduleAPI/CreateSchedule',
                request_serializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.CreateScheduleRequest.SerializeToString,
                response_deserializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.CreateScheduleResponse.FromString,
                _registered_method=True)
        self.DescribeSchedule = channel.unary_unary(
                '/uber.cadence.api.v1.ScheduleAPI/DescribeSchedule',
                request_serializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.DescribeScheduleRequest.SerializeToString,
                response_deserializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.DescribeScheduleResponse.FromString,
                _registered_method=True)
        self.ListSchedules = channel.unary_unary(
                '/uber.cadence.api.v1.ScheduleAPI/ListSchedules',
                request_serializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.ListSchedulesRequest.SerializeToString,
                response_deserializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.ListSchedulesResponse.FromString,
                _registered_method=True)
        self.DeleteSchedule = channel.unary_unary(
                '/uber.cadence.api.v1.ScheduleAPI/DeleteSchedule',
                request_serializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.DeleteScheduleRequest.SerializeToString,
                response_deserializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.DeleteScheduleResponse.FromString,
                _registered_method=True)
        self.PauseSchedule = channel.unary_unary(
                '/uber.cadence.api.v1.ScheduleAPI/PauseSchedule',
                request_serializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.PauseScheduleRequest.SerializeToString,
                response_deserializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.PauseScheduleResponse.FromString,
                _registered_method=True)
        self.UnpauseSchedule = channel.unary_unary(
                '/uber.cadence.api.v1.ScheduleAPI/UnpauseSchedule',
                request_serializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.UnpauseScheduleRequest.SerializeToString,
                response_deserializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.UnpauseScheduleResponse.FromString,
                _registered_method=True)
        self.BackfillSchedule = channel.unary_unary(
                '/uber.cadence.api.v1.ScheduleAPI/BackfillSchedule',
                request_serializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.BackfillScheduleRequest.SerializeToString,
                response_deserializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.BackfillScheduleResponse.FromString,
                _registered_method=True)
        self.UpdateSchedule = channel.unary_unary(
                '/uber.cadence.api.v1.ScheduleAPI/UpdateSchedule',
                request_serializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.UpdateScheduleRequest.SerializeToString,
                response_deserializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.UpdateScheduleResponse.FromString,
                _registered_method=True)


class ScheduleAPIServicer(object):
    """ScheduleAPI provides APIs for managing schedules.
    """

    def CreateSchedule(self, request, context):
        """CreateSchedule creates a new schedule.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeSchedule(self, request, context):
        """DescribeSchedule returns the details and current state of a schedule.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSchedules(self, request, context):
        """ListSchedules returns a list of schedules in a domain.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSchedule(self, request, context):
        """DeleteSchedule deletes a schedule.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseSchedule(self, request, context):
        """PauseSchedule pauses a schedule.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnpauseSchedule(self, request, context):
        """UnpauseSchedule resumes a paused schedule.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BackfillSchedule(self, request, context):
        """BackfillSchedule triggers runs for a historical time range.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSchedule(self, request, context):
        """UpdateSchedule updates the configuration of an existing schedule.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScheduleAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchedule,
                    request_deserializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.CreateScheduleRequest.FromString,
                    response_serializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.CreateScheduleResponse.SerializeToString,
            ),
            'DescribeSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeSchedule,
                    request_deserializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.DescribeScheduleRequest.FromString,
                    response_serializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.DescribeScheduleResponse.SerializeToString,
            ),
            'ListSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSchedules,
                    request_deserializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.ListSchedulesRequest.FromString,
                    response_serializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.ListSchedulesResponse.SerializeToString,
            ),
            'DeleteSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSchedule,
                    request_deserializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.DeleteScheduleRequest.FromString,
                    response_serializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.DeleteScheduleResponse.SerializeToString,
            ),
            'PauseSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseSchedule,
                    request_deserializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.PauseScheduleRequest.FromString,
                    response_serializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.PauseScheduleResponse.SerializeToString,
            ),
            'UnpauseSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.UnpauseSchedule,
                    request_deserializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.UnpauseScheduleRequest.FromString,
                    response_serializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.UnpauseScheduleResponse.SerializeToString,
            ),
            'BackfillSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.BackfillSchedule,
                    request_deserializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.BackfillScheduleRequest.FromString,
                    response_serializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.BackfillScheduleResponse.SerializeToString,
            ),
            'UpdateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSchedule,
                    request_deserializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.UpdateScheduleRequest.FromString,
                    response_serializer=cadence_dot_api_dot_v1_dot_service__schedule__pb2.UpdateScheduleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uber.cadence.api.v1.ScheduleAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('uber.cadence.api.v1.ScheduleAPI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScheduleAPI(object):
    """ScheduleAPI provides APIs for managing schedules.
    """

    @staticmethod
    def CreateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uber.cadence.api.v1.ScheduleAPI/CreateSchedule',
            cadence_dot_api_dot_v1_dot_service__schedule__pb2.CreateScheduleRequest.SerializeToString,
            cadence_dot_api_dot_v1_dot_service__schedule__pb2.CreateScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uber.cadence.api.v1.ScheduleAPI/DescribeSchedule',
            cadence_dot_api_dot_v1_dot_service__schedule__pb2.DescribeScheduleRequest.SerializeToString,
            cadence_dot_api_dot_v1_dot_service__schedule__pb2.DescribeScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uber.cadence.api.v1.ScheduleAPI/ListSchedules',
            cadence_dot_api_dot_v1_dot_service__schedule__pb2.ListSchedulesRequest.SerializeToString,
            cadence_dot_api_dot_v1_dot_service__schedule__pb2.ListSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uber.cadence.api.v1.ScheduleAPI/DeleteSchedule',
            cadence_dot_api_dot_v1_dot_service__schedule__pb2.DeleteScheduleRequest.SerializeToString,
            cadence_dot_api_dot_v1_dot_service__schedule__pb2.DeleteScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uber.cadence.api.v1.ScheduleAPI/PauseSchedule',
            cadence_dot_api_dot_v1_dot_service__schedule__pb2.PauseScheduleRequest.SerializeToString,
            cadence_dot_api_dot_v1_dot_service__schedule__pb2.PauseScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnpauseSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uber.cadence.api.v1.ScheduleAPI/UnpauseSchedule',
            cadence_dot_api_dot_v1_dot_service__schedule__pb2.UnpauseScheduleRequest.SerializeToString,
            cadence_dot_api_dot_v1_dot_service__schedule__pb2.UnpauseScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BackfillSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uber.cadence.api.v1.ScheduleAPI/BackfillSchedule',
            cadence_dot_api_dot_v1_dot_service__schedule__pb2.BackfillScheduleRequest.SerializeToString,
            cadence_dot_api_dot_v1_dot_service__schedule__pb2.BackfillScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uber.cadence.api.v1.ScheduleAPI/UpdateSchedule',
            cadence_dot_api_dot_v1_dot_service__schedule__pb2.UpdateScheduleRequest.SerializeToString,
            cadence_dot_api_dot_v1_dot_service__schedule__pb2.UpdateScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
