# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: uber/cadence/api/v1/visibility.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'uber/cadence/api/v1/visibility.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from uber.cadence.api.v1 import workflow_pb2 as uber_dot_cadence_dot_api_dot_v1_dot_workflow__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$uber/cadence/api/v1/visibility.proto\x12\x13uber.cadence.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"uber/cadence/api/v1/workflow.proto\">\n\x17WorkflowExecutionFilter\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\"\"\n\x12WorkflowTypeFilter\x12\x0c\n\x04name\x18\x01 \x01(\t\"u\n\x0fStartTimeFilter\x12\x31\n\rearliest_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0blatest_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"Q\n\x0cStatusFilter\x12\x41\n\x06status\x18\x01 \x01(\x0e\x32\x31.uber.cadence.api.v1.WorkflowExecutionCloseStatus*\xea\x01\n\x10IndexedValueType\x12\x1e\n\x1aINDEXED_VALUE_TYPE_INVALID\x10\x00\x12\x1d\n\x19INDEXED_VALUE_TYPE_STRING\x10\x01\x12\x1e\n\x1aINDEXED_VALUE_TYPE_KEYWORD\x10\x02\x12\x1a\n\x16INDEXED_VALUE_TYPE_INT\x10\x03\x12\x1d\n\x19INDEXED_VALUE_TYPE_DOUBLE\x10\x04\x12\x1b\n\x17INDEXED_VALUE_TYPE_BOOL\x10\x05\x12\x1f\n\x1bINDEXED_VALUE_TYPE_DATETIME\x10\x06\x42_\n\x17\x63om.uber.cadence.api.v1B\x0fVisibilityProtoP\x01Z1github.com/uber/cadence-idl/go/proto/api/v1;apiv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uber.cadence.api.v1.visibility_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.uber.cadence.api.v1B\017VisibilityProtoP\001Z1github.com/uber/cadence-idl/go/proto/api/v1;apiv1'
  _globals['_INDEXEDVALUETYPE']._serialized_start=433
  _globals['_INDEXEDVALUETYPE']._serialized_end=667
  _globals['_WORKFLOWEXECUTIONFILTER']._serialized_start=130
  _globals['_WORKFLOWEXECUTIONFILTER']._serialized_end=192
  _globals['_WORKFLOWTYPEFILTER']._serialized_start=194
  _globals['_WORKFLOWTYPEFILTER']._serialized_end=228
  _globals['_STARTTIMEFILTER']._serialized_start=230
  _globals['_STARTTIMEFILTER']._serialized_end=347
  _globals['_STATUSFILTER']._serialized_start=349
  _globals['_STATUSFILTER']._serialized_end=430
# @@protoc_insertion_point(module_scope)
